// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IpcServer>>
abstract class IpcServer implements RustOpaqueInterface {
  static Future<IpcServer> bind({required String address}) =>
      RustLib.instance.api.crateApiIpcIpcServerBind(address: address);

  Future<void> close();

  Stream<IpcEvent> events();

  void send({required List<int> message});
}

class IpcEvent {
  final IpcEventKind kind;
  final int? pid;
  final Uint8List payload;
  final String? error;

  const IpcEvent({
    required this.kind,
    this.pid,
    required this.payload,
    this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ pid.hashCode ^ payload.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IpcEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          pid == other.pid &&
          payload == other.payload &&
          error == other.error;
}

enum IpcEventKind { connected, message, disconnected, failed }
